let constants = {
    ACCOUNT_CREATED: "Account created successfully.",
    ADMIN_CREATED: "Admin created successfully",
    ALREADY_REG_SUPERADMIN : "Already registered, please login",
    ALREADY_REG_USER : "Email already registered",
    DELETED_SUCCESSFULLY: "Deleted Successfully",
    EMAIL_REGEX : /^[a-zA-Z0-9.]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/,
    FOUND_NO_User: "No users found",
    INCORRECT_EMAIL: "Email is invalid",
    INCORRECT_PASSWORD: "Password must be contain atleast 8 characters including alphabets, numeric & special characters.",
    NEW_CONF_PASS_MISSMATCH: "New password and Confirm pass mismatched",
    NO_OTP: "No OTP generated",
    NO_SUPERADMIN_FOUND: "No superadmin found",
    NOT_EXIST_WITH_THIS_ID: "Not exist with this Id",
    NOT_DELETED: "Not deleted",
    NOT_UPDATED: "Not updated",
    LOGIN_SUCCESS : "Login Successfully !",
    OTP_EXPIRED: "OTP expired please regenerate new one",
    OTP_FALSE: "OTP not matched",
    OTP_TRUE: "OTP matched",
    MAIL_SENT: " otp sent to your mail",
    PASS_CHANGED: "Password changed successfully",
    PASSWORD_HASH_ERR: "Unable to encrypt pasword.",
    PASSWORD_MATCHED: "Correct Password",
    PASSWORD_UNMATCHED: "Incorrect Mobile or Password",
    PASSWORD_REGEX: /^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/,
    PROVIDE_CONFIRM_PASS: "Please provide confirm password",
    PROVIDE_AUTHOR: "Please provide author",
    PROVIDE_DESCRIPTION: "Please provide description",
    PROVIDE_EMAIL: "Please provide email",
    PROVIDE_EMAIL_OR_PASSWORD: "Please provide email or mobile",
    PROVIDE_ID: "Please provide Id",
    PROVIDE_NEW_PASS: "Please provide new password",
    PROVIDE_OTP: "Please provide OTP",
    PROVIDE_PASS: "Please provide password",
    PROVIDE_PRICE: "Please provide price",
    PROVIDE_TITLE: "Please provide title",
    PROVIDE_NAME: "Please provide name",
    PAYLOAD_VALIDATION_FAIL: "Please provide valid payload",
    SALT_ROUNDS: 5,
    SERVER_ERR: "Someting went wrong",
    TOKEN_CREATE_FAIL: "Unable to create token",
    NO_TOKEN: "Please provide access token",
    NO_USER: "No user found with this email",
    NO_USER_WITH_THIS_EMAIL: "No user found with this email",
    UPDATED_SUCCESSFULLY: "Updated Successfully",
    USER_NOT_VERIFIED: "Number not verified",
    SUPERADMIN_PROFILE_UPDATED: "super admin profile updated successfully",
  
  }
  
  module.exports = constants;